%==========================================================================
% nc_var_fvcom    ---   nc_toolbox
%   Copy attributes of global/an attribute from one file to the other
%
% input  :
%   var_name  --- variable name
%                     
% output :
%   var       --- nc.vars{i}
%
% Siqi Li, SMAST
% 2022-04-06
%
% Updates:
%
%==========================================================================
function var = nc_var_fvcom(var_name)


switch lower(var_name)
    
    % UTM Coordinate
    case 'x'
        var = {'x', 'float', ["node"], ...
                {'long_name', 'nodal x-coordinate'}, ...
                {'units', 'meters'}};
    case 'y'
        var = {'y', 'float', ["node"], ...
                {'long_name', 'nodal y-coordinate'}, ...
                {'units', 'meters'}};        
    case 'xc'
        var = {'xc', 'float', ["nele"], ...
                {'long_name', 'zonal x-coordinate'}, ...
                {'units', 'meters'}};
    case 'yc'
        var = {'yc', 'float', ["nele"], ...
                {'long_name', 'zonal y-coordinate'}, ...
                {'units', 'meters'}};    
    % Geo-referenced Coordinate        
    case 'lon'
        var = {'lon', 'float', ["node"], ...
                {'long_name', 'longitude'}, ...
                {'units', 'degrees_east'}};        
    case 'lat'
        var = {'lat', 'float', ["node"], ...
                {'long_name', 'latitude'}, ...
                {'units', 'degrees_north'}};                 
    case 'lonc'
        var = {'lonc', 'float', ["nele"], ...
                {'long_name', 'zonal longitude'}, ...
                {'units', 'degrees_east'}};        
    case 'latc'
        var = {'latc', 'float', ["nele"], ...
                {'long_name', 'zonal latitude'}, ...
                {'units', 'degrees_north'}};              
    % Grid connection
    case 'nv'
        var = {'nv', 'int', ["nele", "three"], ...
                {'long_name', 'nodes surrounding element'}};   
    % Vertical Coordinate
    case 'siglay'
        var = {'siglay', 'float', ["node", "siglay"], ...
                {'long_name', 'Sigma Layers'}, ...
                {'positive', 'up'},...
                {'valid_min', -1.0}, ...
                {'valid_max', -0.0}};    
    case 'siglev'
        var = {'siglev', 'float', ["node", "siglev"], ...
                {'long_name', 'Sigma Levels'}, ...
                {'positive', 'up'},...
                {'valid_min', -1.0}, ...
                {'valid_max', -0.0}};    
    % Time variables
    case 'time'
        var = {'time', 'float', ["time"], ...
                {'long_name', 'time'}, ...
                {'units', 'Days since 1858-11-17 00:00:00'}, ...
                {'format', 'modified julian day (MJD)'}};  
    case 'itime'
        var = {'Itime', 'int', ["time"], ...
                {'units', 'Days since 1858-11-17 00:00:00'}, ...
                {'format', 'modified julian day (MJD)'}};   
    case 'itime2'
        var = {'Itime2', 'int', ["time"], ...
                {'units', 'msec since 00:00:00'}, ...
                {'format', 'modified julian day (MJD)'}};     
    case 'times'
        var = {'Itime', 'char', ["DateStrLen", "time"], ...
                {'format', 'yyyy-mm-ddTHH:MM:SS.xxxxxx'}};               
    % Variables on node        
    case 'h'
        var = {'h', 'float', ["node"], ...
                {'long_name', 'Bathymetry'}, ...
                {'units', 'meters'}, ...
                {'positive', 'down'}};   
    case 'zeta'
        var = {'zeta', 'float', ["node", "time"], ...
                {'long_name', 'Water surface elevation'}, ...
                {'units', 'meters'}, ...
                {'positive', 'up'}};       
    case 'temp'
        var = {'temp', 'float', ["node", "siglay", "time"], ...
                {'long_name', 'Temperature'}, ...
                {'units', 'degree_C'}};                   
    case 'salinity'
        var = {'salinity', 'float', ["node", "siglay", "time"], ...
                {'long_name', 'Salinity'}, ...
                {'units', 'PSU'}}; 
    case 'omega'
        var = {'omega', 'float', ["node", "siglev", "time"], ...
                {'long_name', 'Vertical Sigma Coordinate Velocity'}, ...
                {'units', 's-1'}};            
    % Variables on cell        
    case 'ua'
        var = {'ua', 'float', ["nele", "time"], ...
                {'long_name', 'Vertically Averaged x-velocity'}, ...
                {'units', 'm/s'}};   
    case 'va'
        var = {'va', 'float', ["nele", "time"], ...
                {'long_name', 'Vertically Averaged y-velocity'}, ...
                {'units', 'm/s'}}; 
    case 'u'
        var = {'u', 'float', ["nele", "siglay", "time"], ...
                {'long_name', 'Eastward Water Velocity'}, ...
                {'units', 'm/s'}};            
    case 'v'
        var = {'v', 'float', ["nele", "siglay", "time"], ...
                {'long_name', 'Northward Water Velocity'}, ...
                {'units', 'm/s'}};   
    case 'ww'
        var = {'ww', 'float', ["nele", "siglay", "time"], ...
                {'long_name', 'Upward Water Velocity'}, ...
                {'units', 'm/s'}};            
    otherwise
        error(['Unknown variable ' var_name])
        
end

end
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            
            